// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    accounts,
    categories,
    ledgerEntries,
  ];
  late final Shape0 accounts = Shape0(
    source: i0.VersionedTable(
      entityName: 'accounts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK(type BETWEEN 0 AND 3)',
        'CHECK(length(trim(name)) BETWEEN 1 AND 80)',
        'CHECK(length(trim(normalized_name)) > 0)',
      ],
      columns: [_column_0, _column_1, _column_2, _column_3, _column_4],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 categories = Shape1(
    source: i0.VersionedTable(
      entityName: 'categories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK(kind IN (0, 1))',
        'CHECK(parent_id IS NULL OR parent_id <> id)',
        'CHECK(length(trim(name)) BETWEEN 1 AND 80)',
        'CHECK(length(trim(normalized_name)) BETWEEN 1 AND 80)',
        'CHECK(length(trim(icon_key)) BETWEEN 1 AND 40)',
        'CHECK(sort_order BETWEEN 0 AND 1000000)',
        'CHECK(system_key IS NULL OR length(trim(system_key)) BETWEEN 1 AND 80)',
      ],
      columns: [
        _column_0,
        _column_5,
        _column_6,
        _column_1,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_4,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 ledgerEntries = Shape2(
    source: i0.VersionedTable(
      entityName: 'ledger_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK(kind BETWEEN 0 AND 3)',
        'CHECK(amount BETWEEN 1 AND 999999999999)',
        'CHECK(occurred_day BETWEEN 20000101 AND 99991231)',
        'CHECK(length(note) <= 500)',
        'CHECK((kind IN (0, 1) AND destination_account_id IS NULL AND category_id IS NOT NULL)OR(kind = 2 AND destination_account_id IS NOT NULL AND destination_account_id <> account_id AND category_id IS NULL)OR(kind = 3 AND destination_account_id IS NULL AND category_id IS NULL))',
      ],
      columns: [
        _column_0,
        _column_6,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_4,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get normalizedName =>
      columnsByName['normalized_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get type =>
      columnsByName['type']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_0(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'id',
      aliasedName,
      false,
      hasAutoIncrement: true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL PRIMARY KEY AUTOINCREMENT',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'normalized_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL UNIQUE',
    );
i1.GeneratedColumn<int> _column_3(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'type',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_4(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get parentId =>
      columnsByName['parent_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get normalizedName =>
      columnsByName['normalized_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get iconKey =>
      columnsByName['icon_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isArchived =>
      columnsByName['is_archived']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get systemKey =>
      columnsByName['system_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_5(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'parent_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL REFERENCES categories(id)ON DELETE RESTRICT',
    );
i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'kind',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'normalized_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'icon_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_archived',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_archived IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_10(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'sort_order',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'system_key',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL UNIQUE',
    );
i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get accountId =>
      columnsByName['account_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get destinationAccountId =>
      columnsByName['destination_account_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get amount =>
      columnsByName['amount']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get categoryId =>
      columnsByName['category_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get note =>
      columnsByName['note']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get occurredDay =>
      columnsByName['occurred_day']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_13(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'account_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES accounts(id)',
    );
i1.GeneratedColumn<int> _column_14(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'destination_account_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL REFERENCES accounts(id)',
    );
i1.GeneratedColumn<int> _column_15(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'amount',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_16(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'category_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL REFERENCES categories(id)',
    );
i1.GeneratedColumn<String> _column_17(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'note',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'\'',
      defaultValue: const i1.CustomExpression('\'\''),
    );
i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'occurred_day',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    accounts,
    categories,
    ledgerEntries,
  ];
  late final Shape3 accounts = Shape3(
    source: i0.VersionedTable(
      entityName: 'accounts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK(type BETWEEN 0 AND 3)',
        'CHECK(length(trim(name)) BETWEEN 1 AND 80)',
        'CHECK(length(trim(normalized_name)) > 0)',
      ],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_9,
        _column_4,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 categories = Shape1(
    source: i0.VersionedTable(
      entityName: 'categories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK(kind IN (0, 1))',
        'CHECK(parent_id IS NULL OR parent_id <> id)',
        'CHECK(length(trim(name)) BETWEEN 1 AND 80)',
        'CHECK(length(trim(normalized_name)) BETWEEN 1 AND 80)',
        'CHECK(length(trim(icon_key)) BETWEEN 1 AND 40)',
        'CHECK(sort_order BETWEEN 0 AND 1000000)',
        'CHECK(system_key IS NULL OR length(trim(system_key)) BETWEEN 1 AND 80)',
      ],
      columns: [
        _column_0,
        _column_5,
        _column_6,
        _column_1,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_4,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 ledgerEntries = Shape2(
    source: i0.VersionedTable(
      entityName: 'ledger_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK(kind BETWEEN 0 AND 3)',
        'CHECK((kind IN (0, 1, 2) AND amount BETWEEN 1 AND 999999999999)OR(kind = 3 AND amount BETWEEN -999999999999 AND 999999999999 AND amount <> 0))',
        'CHECK(occurred_day BETWEEN 20000101 AND 99991231)',
        'CHECK(length(note) <= 500)',
        'CHECK((kind IN (0, 1) AND destination_account_id IS NULL AND category_id IS NOT NULL)OR(kind = 2 AND destination_account_id IS NOT NULL AND destination_account_id <> account_id AND category_id IS NULL)OR(kind = 3 AND destination_account_id IS NULL AND category_id IS NULL))',
      ],
      columns: [
        _column_0,
        _column_6,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_4,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get normalizedName =>
      columnsByName['normalized_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get type =>
      columnsByName['type']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isArchived =>
      columnsByName['is_archived']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    accounts,
    categories,
    ledgerEntries,
    ledgerAllocations,
  ];
  late final Shape3 accounts = Shape3(
    source: i0.VersionedTable(
      entityName: 'accounts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK(type BETWEEN 0 AND 3)',
        'CHECK(length(trim(name)) BETWEEN 1 AND 80)',
        'CHECK(length(trim(normalized_name)) > 0)',
      ],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_9,
        _column_4,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 categories = Shape1(
    source: i0.VersionedTable(
      entityName: 'categories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK(kind IN (0, 1))',
        'CHECK(parent_id IS NULL OR parent_id <> id)',
        'CHECK(length(trim(name)) BETWEEN 1 AND 80)',
        'CHECK(length(trim(normalized_name)) BETWEEN 1 AND 80)',
        'CHECK(length(trim(icon_key)) BETWEEN 1 AND 40)',
        'CHECK(sort_order BETWEEN 0 AND 1000000)',
        'CHECK(system_key IS NULL OR length(trim(system_key)) BETWEEN 1 AND 80)',
      ],
      columns: [
        _column_0,
        _column_5,
        _column_6,
        _column_1,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_4,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 ledgerEntries = Shape4(
    source: i0.VersionedTable(
      entityName: 'ledger_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK(kind BETWEEN 0 AND 3)',
        'CHECK((kind IN (0, 1, 2) AND amount BETWEEN 1 AND 999999999999)OR(kind = 3 AND amount BETWEEN -999999999999 AND 999999999999 AND amount <> 0))',
        'CHECK(occurred_day BETWEEN 20000101 AND 99991231)',
        'CHECK(length(note) <= 500)',
        'CHECK((kind IN (0, 1) AND destination_account_id IS NULL)OR(kind = 2 AND destination_account_id IS NOT NULL AND destination_account_id <> account_id)OR(kind = 3 AND destination_account_id IS NULL))',
      ],
      columns: [
        _column_0,
        _column_6,
        _column_13,
        _column_14,
        _column_15,
        _column_17,
        _column_18,
        _column_4,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 ledgerAllocations = Shape5(
    source: i0.VersionedTable(
      entityName: 'ledger_allocations',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(entry_id, position)',
        'UNIQUE(entry_id, category_id)',
        'CHECK(position BETWEEN 0 AND 49)',
        'CHECK(amount BETWEEN 1 AND 999999999999)',
      ],
      columns: [_column_19, _column_20, _column_21, _column_15],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get accountId =>
      columnsByName['account_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get destinationAccountId =>
      columnsByName['destination_account_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get amount =>
      columnsByName['amount']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get note =>
      columnsByName['note']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get occurredDay =>
      columnsByName['occurred_day']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get entryId =>
      columnsByName['entry_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get position =>
      columnsByName['position']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get categoryId =>
      columnsByName['category_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get amount =>
      columnsByName['amount']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_19(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'entry_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL REFERENCES ledger_entries(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<int> _column_20(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'position',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'category_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL REFERENCES categories(id)ON DELETE RESTRICT',
    );

final class Schema5 extends i0.VersionedSchema {
  Schema5({required super.database}) : super(version: 5);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    accounts,
    categories,
    ledgerEntries,
    ledgerAllocations,
  ];
  late final Shape6 accounts = Shape6(
    source: i0.VersionedTable(
      entityName: 'accounts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK(type BETWEEN 0 AND 3)',
        'CHECK(length(trim(name)) BETWEEN 1 AND 80)',
        'CHECK(length(trim(normalized_name)) > 0)',
      ],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_22,
        _column_9,
        _column_4,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 categories = Shape1(
    source: i0.VersionedTable(
      entityName: 'categories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK(kind IN (0, 1))',
        'CHECK(parent_id IS NULL OR parent_id <> id)',
        'CHECK(length(trim(name)) BETWEEN 1 AND 80)',
        'CHECK(length(trim(normalized_name)) BETWEEN 1 AND 80)',
        'CHECK(length(trim(icon_key)) BETWEEN 1 AND 40)',
        'CHECK(sort_order BETWEEN 0 AND 1000000)',
        'CHECK(system_key IS NULL OR length(trim(system_key)) BETWEEN 1 AND 80)',
      ],
      columns: [
        _column_0,
        _column_5,
        _column_6,
        _column_1,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_4,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 ledgerEntries = Shape4(
    source: i0.VersionedTable(
      entityName: 'ledger_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK(kind BETWEEN 0 AND 3)',
        'CHECK((kind IN (0, 1, 2) AND amount BETWEEN 1 AND 999999999999)OR(kind = 3 AND amount BETWEEN -999999999999 AND 999999999999 AND amount <> 0))',
        'CHECK(occurred_day BETWEEN 20000101 AND 99991231)',
        'CHECK(length(note) <= 500)',
        'CHECK((kind IN (0, 1) AND destination_account_id IS NULL)OR(kind = 2 AND destination_account_id IS NOT NULL AND destination_account_id <> account_id)OR(kind = 3 AND destination_account_id IS NULL))',
      ],
      columns: [
        _column_0,
        _column_6,
        _column_13,
        _column_14,
        _column_15,
        _column_17,
        _column_18,
        _column_4,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 ledgerAllocations = Shape5(
    source: i0.VersionedTable(
      entityName: 'ledger_allocations',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(entry_id, position)',
        'UNIQUE(entry_id, category_id)',
        'CHECK(position BETWEEN 0 AND 49)',
        'CHECK(amount BETWEEN 1 AND 999999999999)',
      ],
      columns: [_column_19, _column_20, _column_21, _column_15],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get normalizedName =>
      columnsByName['normalized_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get type =>
      columnsByName['type']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get balanceGroup =>
      columnsByName['balance_group']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isArchived =>
      columnsByName['is_archived']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_22(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'balance_group',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (balance_group IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );

final class Schema6 extends i0.VersionedSchema {
  Schema6({required super.database}) : super(version: 6);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    accounts,
    categories,
    ledgerEntries,
    ledgerAllocations,
    budgets,
    budgetCategories,
  ];
  late final Shape6 accounts = Shape6(
    source: i0.VersionedTable(
      entityName: 'accounts',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK(type BETWEEN 0 AND 3)',
        'CHECK(length(trim(name)) BETWEEN 1 AND 80)',
        'CHECK(length(trim(normalized_name)) > 0)',
      ],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_22,
        _column_9,
        _column_4,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 categories = Shape1(
    source: i0.VersionedTable(
      entityName: 'categories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK(kind IN (0, 1))',
        'CHECK(parent_id IS NULL OR parent_id <> id)',
        'CHECK(length(trim(name)) BETWEEN 1 AND 80)',
        'CHECK(length(trim(normalized_name)) BETWEEN 1 AND 80)',
        'CHECK(length(trim(icon_key)) BETWEEN 1 AND 40)',
        'CHECK(sort_order BETWEEN 0 AND 1000000)',
        'CHECK(system_key IS NULL OR length(trim(system_key)) BETWEEN 1 AND 80)',
      ],
      columns: [
        _column_0,
        _column_5,
        _column_6,
        _column_1,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_4,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 ledgerEntries = Shape4(
    source: i0.VersionedTable(
      entityName: 'ledger_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK(kind BETWEEN 0 AND 3)',
        'CHECK((kind IN (0, 1, 2) AND amount BETWEEN 1 AND 999999999999)OR(kind = 3 AND amount BETWEEN -999999999999 AND 999999999999 AND amount <> 0))',
        'CHECK(occurred_day BETWEEN 20000101 AND 99991231)',
        'CHECK(length(note) <= 500)',
        'CHECK((kind IN (0, 1) AND destination_account_id IS NULL)OR(kind = 2 AND destination_account_id IS NOT NULL AND destination_account_id <> account_id)OR(kind = 3 AND destination_account_id IS NULL))',
      ],
      columns: [
        _column_0,
        _column_6,
        _column_13,
        _column_14,
        _column_15,
        _column_17,
        _column_18,
        _column_4,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 ledgerAllocations = Shape5(
    source: i0.VersionedTable(
      entityName: 'ledger_allocations',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(entry_id, position)',
        'UNIQUE(entry_id, category_id)',
        'CHECK(position BETWEEN 0 AND 49)',
        'CHECK(amount BETWEEN 1 AND 999999999999)',
      ],
      columns: [_column_19, _column_20, _column_21, _column_15],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 budgets = Shape7(
    source: i0.VersionedTable(
      entityName: 'budgets',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'CHECK(period_kind BETWEEN 0 AND 2)',
        'CHECK(start_day BETWEEN 20000101 AND 99991231 AND(CAST(start_day / 100 AS INTEGER) % 100)BETWEEN 1 AND 12 AND(start_day % 100)BETWEEN 1 AND CASE(CAST(start_day / 100 AS INTEGER) % 100)WHEN 1 THEN 31 WHEN 2 THEN CASE WHEN(CAST(start_day / 10000 AS INTEGER) % 400 = 0)OR(CAST(start_day / 10000 AS INTEGER) % 4 = 0 AND CAST(start_day / 10000 AS INTEGER) % 100 <> 0)THEN 29 ELSE 28 END WHEN 3 THEN 31 WHEN 4 THEN 30 WHEN 5 THEN 31 WHEN 6 THEN 30 WHEN 7 THEN 31 WHEN 8 THEN 31 WHEN 9 THEN 30 WHEN 10 THEN 31 WHEN 11 THEN 30 WHEN 12 THEN 31 ELSE 0 END)',
        'CHECK(end_day BETWEEN 20000101 AND 99991231 AND(CAST(end_day / 100 AS INTEGER) % 100)BETWEEN 1 AND 12 AND(end_day % 100)BETWEEN 1 AND CASE(CAST(end_day / 100 AS INTEGER) % 100)WHEN 1 THEN 31 WHEN 2 THEN CASE WHEN(CAST(end_day / 10000 AS INTEGER) % 400 = 0)OR(CAST(end_day / 10000 AS INTEGER) % 4 = 0 AND CAST(end_day / 10000 AS INTEGER) % 100 <> 0)THEN 29 ELSE 28 END WHEN 3 THEN 31 WHEN 4 THEN 30 WHEN 5 THEN 31 WHEN 6 THEN 30 WHEN 7 THEN 31 WHEN 8 THEN 31 WHEN 9 THEN 30 WHEN 10 THEN 31 WHEN 11 THEN 30 WHEN 12 THEN 31 ELSE 0 END)',
        'CHECK(start_day <= end_day)',
        'CHECK((period_kind = 0 AND(start_day % 100)= 1 AND CAST(start_day / 100 AS INTEGER) = CAST(end_day / 100 AS INTEGER) AND(end_day % 100)= CASE(CAST(start_day / 100 AS INTEGER) % 100)WHEN 1 THEN 31 WHEN 2 THEN CASE WHEN(CAST(start_day / 10000 AS INTEGER) % 400 = 0)OR(CAST(start_day / 10000 AS INTEGER) % 4 = 0 AND CAST(start_day / 10000 AS INTEGER) % 100 <> 0)THEN 29 ELSE 28 END WHEN 3 THEN 31 WHEN 4 THEN 30 WHEN 5 THEN 31 WHEN 6 THEN 30 WHEN 7 THEN 31 WHEN 8 THEN 31 WHEN 9 THEN 30 WHEN 10 THEN 31 WHEN 11 THEN 30 WHEN 12 THEN 31 ELSE 0 END)OR(period_kind = 1 AND(start_day % 10000)= 101 AND(end_day % 10000)= 1231 AND CAST(start_day / 10000 AS INTEGER) = CAST(end_day / 10000 AS INTEGER))OR period_kind = 2)',
        'CHECK(limit_amount BETWEEN 1 AND 999999999999)',
        'CHECK(length(trim(name)) BETWEEN 1 AND 80)',
        'CHECK(length(trim(normalized_name)) BETWEEN 1 AND 80)',
        'CHECK(updated_at >= created_at)',
      ],
      columns: [
        _column_0,
        _column_23,
        _column_24,
        _column_25,
        _column_1,
        _column_7,
        _column_26,
        _column_4,
        _column_12,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 budgetCategories = Shape8(
    source: i0.VersionedTable(
      entityName: 'budget_categories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(budget_id, category_id)'],
      columns: [_column_27, _column_21],
      attachedDatabase: database,
    ),
    alias: null,
  );
}

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get id =>
      columnsByName['id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get periodKind =>
      columnsByName['period_kind']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get startDay =>
      columnsByName['start_day']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get endDay =>
      columnsByName['end_day']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get name =>
      columnsByName['name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get normalizedName =>
      columnsByName['normalized_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get limitAmount =>
      columnsByName['limit_amount']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_23(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'period_kind',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_24(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'start_day',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'end_day',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'limit_amount',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get budgetId =>
      columnsByName['budget_id']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get categoryId =>
      columnsByName['category_id']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<int> _column_27(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'budget_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL REFERENCES budgets(id)ON DELETE CASCADE',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      case 4:
        final schema = Schema5(database: database);
        final migrator = i1.Migrator(database, schema);
        await from4To5(migrator, schema);
        return 5;
      case 5:
        final schema = Schema6(database: database);
        final migrator = i1.Migrator(database, schema);
        await from5To6(migrator, schema);
        return 6;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(
    from1To2: from1To2,
    from2To3: from2To3,
    from3To4: from3To4,
    from4To5: from4To5,
    from5To6: from5To6,
  ),
);
